package com.fluidpay.sdk;

public enum ConnectionType {
    CREATEKEY, GETKEYS, DELETEKEY,
    CUSTOMER, CUSTOMERID, CUSTOMERUPDATE, CUSTOMERSEARCH,
    CUSTOMERADDRESS, CUSTOMERADDRESSES, CUSTOMERADDRESSID,
    CUSTOMERCARD, CUSTOMERCARDID,
    CUSTOMERACH, CUSTOMERACHID,
    CUSTOMERTOKEN, CUSTOMERTOKENID,
    CUSTOMERAPPLEPAY, CUSTOMERGOOGLEPAY,
    CUSTOMERPAYMENT, CUSTOMERPAYMENTID, // Legacy support
    ADDON, ADDONS, ADDONID,
    DISCOUNT, DISCOUNTS, DISCOUNTID,
    PLAN, PLANS, PLANID,
    SUBSCRIPTION, SUBSCRIPTIONID, SUBSCRIPTIONSEARCH,
    SUBSCRIPTIONPAUSED, SUBSCRIPTIONPASTDUE, SUBSCRIPTIONCANCELLED, SUBSCRIPTIONACTIVE, SUBSCRIPTIONCOMPLETED,
    TERMINALS,
    TRANSACTION, TRANSACTIONSTATUS, TRANSACTIONQUERY, TRANSACTIONCAPTURE, TRANSACTIONVOID, TRANSACTIONREFUND,
    CHANGEPASSWORD, USER, USERS, USERID;
}


