package com.fluidpay.sdk;

public enum ConnectionType {
    CREATEKEY, GETKEYS, DELETEKEY,
    OBTAINJWT, FORGOTTENUSERNAME, FORGOTTENPASSWORD, PASSWORDRESET, TOKENLOGOUT,
    CUSTOMER, CUSTOMERID, CUSTOMERUPDATE, CUSTOMERSEARCH,
    CUSTOMERADDRESS, CUSTOMERADDRESSES, CUSTOMERADDRESSID,
    CUSTOMERCARD, CUSTOMERCARDID,
    CUSTOMERACH, CUSTOMERACHID,
    CUSTOMERTOKEN, CUSTOMERTOKENID,
    CUSTOMERAPPLEPAY, CUSTOMERGOOGLEPAY,
    ADDON, ADDONS, ADDONID,
    DISCOUNT, DISCOUNTS, DISCOUNTID,
    PLAN, PLANS, PLANID,
    SUBSCRIPTION, SUBSCRIPTIONID,
    TERMINALS,
    TRANSACTION, TRANSACTIONSTATUS, TRANSACTIONQUERY, TRANSACTIONCAPTURE, TRANSACTIONVOID, TRANSACTIONREFUND,
    CHANGEPASSWORD, USER, USERS, USERID;
}


